### ISSUE TITLE
Global Admin Dashboard

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#182]
When a global administrator logs in - the first page they should see should look like this: https://mongodb.invisionapp.com/share/MYXRXC2T2H3#/screens/422348690_Global_Admin-Home-Dashboard

All agencies are shown (and they should be shown in alphabetical order - the design is not in that order). 

Each Agency has a name; number of boardings; number of violations; compliance rate; and a link to view boardings filtered by that agency. 

The compliance rate is:
(number of boardings with no citations or warnings)/(total number of boardings)*100 as a percentage
e.g. if there were 10 boardings total and 2 had violations, the compliance rate is 80%
 
The boardings and violations and compliance rate should be calculated on the boardings in the date picker - which should default to the last 7 days.

The Agency name is a link to the Agency dashboard (what is currently called "global dashboard').

**Comment by jsdmaria** [comment]
Was re-estimated because of task complexity. We need to add sub-tasks:
- Add new markup for Dashboards pages
- Change agencies (header) page according to new designs
- Add new Stitch func for Dashboard agencies
- Add new routing to go to agency charts page (when user clicks on agency's name in table row)
