### ISSUE TITLE
Should be an "Add New Agency" button on Agencies page for global admins

### ISSUE THREAD

**Issue by MikeyDubs** [WildAid/o-fish-web#194]
Issue - no "Add New Agency" button:

![Screen Shot 2020-09-16 at 11 06 21 PM](https://user-images.githubusercontent.com/49571712/93415395-65bb7b80-f871-11ea-8bfb-77e01306730f.png)

Should match design:

![Screen Shot 2020-09-16 at 11 06 49 PM](https://user-images.githubusercontent.com/49571712/93415442-7ff55980-f871-11ea-876a-842ab4737b90.png)

**Comment by evayde** [comment]
There's a confusion about who a "global admin" is. There is a check on line 158 of the `agencies.component.js` where it says `isAdmin && !isAgencyAdmin`. This seems to be wrong. What would be the correct check for the admin that ought to see the button? I am guessing `isAdmin`, because of line 118: 

```
if (authService.user.global.admin) {
  this.loadData({ isAdmin: true });
}
```

I am adding a PR for this.

**Comment by Sheeri** [comment]
This was done by @jsdmaria but not closed, so I am closing it now.
