### ISSUE TITLE
Unit test for logging into the web app

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#317]
Is your feature request related to a problem? Please describe.
We would like to start adding unit tests for components in our app.

Describe the solution you'd like
A test in the directory src/_ _ tests _ _ that tests logging into the app. And any accompanying necessary changes; e.g. adding enzyme if that's what we will use.

**Comment by lenmorld** [comment]
Hi @Sheeri 
I would like to take a stab at this.

I'm actually thinking of [React Testing Library](https://testing-library.com/docs/dom-testing-library/intro/) actually, since it's becoming a more popular, modern approach to React testing.
One advantage is that it's closer to use cases (find by text, labels), rather than implementation details (set props).
It also relies on Jest, so we can take advantage of Jest matchers

I also propose a structure for co-located unit tests, and top-level `test/` for integration tests
https://medium.com/@JeffLombardJr/organizing-tests-in-jest-17fc431ff850
Co-located unit tests make it easier to import the component being tested

**Comment by Sheeri** [comment]
apologies for the late notice, but I've assigned this to you! And yes, co-located would be best.
