### ISSUE TITLE
When Crew license # doesn't exist, Crew member page 'name' is "N/A"

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#322]
**Describe the bug**

**To Reproduce**
1. Create a boarding record where there is a crew member with a name but no license
2. Login to the web interface, click "Boarding Records" -> Crew
3. Choose the crew member without a license
4. See that the name is "N/A"

**Expected behavior**
The name should properly appear

**Screenshots**
Here's an example of the "Boarding Records" -> Crew page:
![Screen Shot 2020-10-16 at 10 19 51 AM](https://user-images.githubusercontent.com/1767528/96270450-ad7d1200-0f99-11eb-84c5-a8778fa32c02.png)

And when I click on "Stowaway" here's what I see:
![Screen Shot 2020-10-16 at 10 19 59 AM](https://user-images.githubusercontent.com/1767528/96270455-af46d580-0f99-11eb-9f77-bacc65ce2e08.png)

(instead of N/A it should say "Stowaway" at the top)

**Comment by ayushjainrksh** [comment]
This is because the application uses query parameters to find if the member is a captain. There are 2 solutions to this problem: 

### Short term(to fix this problem): 
1. Modify `isCaptain` variable in https://github.com/WildAid/o-fish-web/blob/14fbb743b9061e79ac4a48c8b9eb63a9194f66c6/src/components/crew/crew-view/crew-view.component.js#L54
to identify if the member is actually a captain or not. 

2. Send captainName/crewName to https://github.com/WildAid/o-fish-web/blob/14fbb743b9061e79ac4a48c8b9eb63a9194f66c6/src/components/crew/crew-view/crew-view.component.js#L75-L77
if licenceNumber is undefined.

### Long term: 
The query parameters in the URL should be a unique id (such as MongoDB id). Sending `captainName/crewName` in the URL can be problematic in case of duplicate names. Moreover, the `licenceNumber` is optional as can be seen in this issue, and thus cannot be used to query the document.

**Comment by sourabhbagrecha** [comment]
I agree @ayushjainrksh, the current URLs are highly problematic and causing problems to various other routes/components as well. I think we need to fix the complete navigation side of things before moving forward, though we can make small changes, but the current approach is neither scalable nor consistent across the application.

**Comment by Sheeri** [comment]
I'm unsure how this relates -  the crew page shows the proper data, except for the crew member's name. It seems as though the query is able to retrieve the proper data, but is not displaying the name properly.

Can you say more about how the URL navigation is related to the vessels, boardings, violations, etc. showing up properly on the page, but the crew memeber's name showing up as 'N/A'? 

Thanks!

As a note: 
We are not worried about duplicate names, as we search on name and license number. We are OK with 2 people who have the same name and also have no license number, being treated as the same person. It is not a common case to that a crew member does not have a license number.

The current approach was designed so that end users can copy and paste a URL and send it to another team member. In this way they are able to share results with another person, without having to say "Search for vessels that include 'boat' in the name with a filter of 'red' and you will get the report of 100 different vessels." - in this case, it would be less than ideal to put 100 record IDs into the URL.

**Comment by ayushjainrksh** [comment]
@Sheeri I've created a PR that solves this issue.

The URL navigation isn't exactly the problem here. It is a larger problem that results in several edge cases to fail(such as duplicate names). In this particular case, the query wasn't able to identify if the crew member is a captain because the `licence number` was absent. Also, the crew name/captain name wasn't sent to the service in absence of `licence number`.

**Comment by ayushjainrksh** [comment]
Why are we using a JSON query string instead of the standard query string? It feels counterintuitive and fails in some cases. One example is when you apply `risk: red` and `risk: amber` together, only one is applied at a time.

**Comment by Sheeri** [comment]
@ayushjainrksh - Can you open another issue to address JSON query string vs. standard query string? That's a deeper issue that we should absolutely look into and make sure we consciously choose the right query string.

**Comment by ayushjainrksh** [comment]
Sure
