### ISSUE TITLE
Web: Allow each agency to define their own menu items for the mobile apps

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#34]
Top n flag state, Activity, Fishery, Gear, Catch Species, Violations

**Comment by Sheeri** [comment]
Design is in progress.

**Comment by Sheeri** [comment]
https://docs.google.com/document/d/1rDXmdlB3lfqAb7uAhR1u96LbyNaUyl3_2t2O_C0kI_E/edit?pli=1#bookmark=id.kpbcu8gfn5wz is where the “Web App - Form Data” design description is

e.g. global admins see this for the activity section: Activity
Since “Activity” has 3 fields in it, it now has its own section in the side nav
Activity (empty list)
Add Activity
You can do this individually or by uploading a CSV. See Catch or Violations for CSV upload design
Activity (activities added)
Edit Activity
Delete Activity
